// plugins {
//   id "com.github.spotbugs" version "1.6.11"
// }


plugins {
    id 'pmd'
}




apply plugin: 'application'
apply plugin: 'jacoco'


mainClassName = 'Main'


// In this section you declare where to find the dependencies of your project
repositories {
    mavenCentral()
}

// In this section you declare the dependencies for your production and test code
dependencies {
    dependencies 
    testImplementation 'org.junit.jupiter:junit-jupiter:5.9.1'

 testImplementation 'org.junit.vintage:junit-vintage-engine:5.9.1'
    implementation "junit:junit:4.12"
    implementation files('cls/')
}

apply plugin: "pmd"
pmd {
  ignoreFailures = true 
  sourceSets = [sourceSets.main]
  reportsDir = file("$project.buildDir/reports/pmd")
  ruleSets = []
  ruleSetConfig = resources.text.fromFile('ruleset.xml')
}

/////////////////////////////////////////////////////////////////////////
// Configure Checkstyle
/////////////////////////////////////////////////////////////////////////
// apply plugin: 'checkstyle'
// checkstyle {
//   // Keep checkstyle a little quieter
//   ignoreFailures = true
//   showViolations = false
// }

// tasks.withType(Checkstyle) {
//   reports {
//     html.enabled = true
//     xml.enabled = false
//   }
// }
// checkstyle {
//     toolVersion = "8.8"
// }


///////////////////////////////////////////////////////////////////////////
// Configure SpotBugs
///////////////////////////////////////////////////////////////////////////

// spotbugs {
//   toolVersion = '3.1.12'
// }

// // To generate an HTML report instead of XML
// tasks.withType(com.github.spotbugs.SpotBugsTask) {
//   reports {
//     xml.enabled = false
//     html.enabled = true
//   }
// }